// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_query.sql

package repo

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, name, nis, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nis,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
